### ISSUE TITLE
Design Home Page with option to Create Order or Track Order

### ISSUE THREAD

**Issue by ampslive** [ampslive/EasyLaundry#1]
When user, opens application, they see the following options...

- [x] Button for Create Order for Laundry
- [x] Button for Tracking Order
- [x] Image Button should be used

**Comment by Raphael-Evan** [comment]
![Screenshot 2023-10-05 081831](https://github.com/ampslive/EasyLaundry/assets/134363792/d7a9aa68-768f-4bf6-a3da-3de278e3e354)
