### ISSUE TITLE
Click on Create Order to navigate to New Order Page

### ISSUE THREAD

**Issue by ampslive** [ampslive/EasyLaundry#2]
When user, clicks on Create Order button...

- [x] Navigate to New Order Page
- [x] New Order Page should contain the following fields...
    - [x] Dropdown for LaundryType (Wash, DryClean, Ironing, Wash + Ironing) 
    - [x] Textbox with ClothType (Shirt, T-Shirt, Trouser, Dress, Sari, Other)
    - [x] Input field for quantity
    - [x] Input field for User Information (Customer Name)
    - [x] Input field for User Information (Customer Phone)
    - [x] Input field for User Information (Customer Address)

- [x] After Order is Created, user should get the following information on the screen...
    - [x] Order Id
    - [x] Order Status [Pending, Confirmed, In Progress, Completed]
        - [x] By default, all new orders will be in Pending state
    - [x] Order Details
    - [x] Order Completion Date [TodaysDate + 3days]

### Tech Specs
- [x] Create View
- [x] Create Order Controller
- [x] Create Order Model
- [x] Create Database

**Comment by Raphael-Evan** [comment]
![Screenshot 2023-10-05 081843](https://github.com/ampslive/EasyLaundry/assets/134363792/518d228d-9abd-4dcc-8f9b-0b7f0c7a74eb)
![Screenshot 2023-10-05 081913](https://github.com/ampslive/EasyLaundry/assets/134363792/bd8456c4-963c-4902-af98-8fe77d5fd4dc)
![Screenshot 2023-10-05 081923](https://github.com/ampslive/EasyLaundry/assets/134363792/b41d05c9-0d58-499e-adfd-7d468ce3574f)
