### ISSUE TITLE
Laundry Man should be able to view all orders

### ISSUE THREAD

**Issue by ampslive** [ampslive/EasyLaundry#4]
As a laundry person, should be able to...

- [x] Navigate to a separate page to view all orders
- [x] Select any of the above orders, and change the order status dropdown/button from...
    - [x] Pending => Confirmed
    - [x] Confirmed => InProgress
    - [x] InProgress => Completed
- [x] If Order is in `Pending/Confirmed/InProgress` state, the due date can be modified and saved
- [x] If Order is in 'Completed' state, the due date cannot be modified

**Comment by Raphael-Evan** [comment]
![Screenshot 2023-10-05 090604](https://github.com/ampslive/EasyLaundry/assets/134363792/d93b3b67-906d-4918-b545-18792ffc2a30)
![Screenshot 2023-10-05 082011](https://github.com/ampslive/EasyLaundry/assets/134363792/32a76b8b-7e66-4fc8-9e0c-372484ee76c0)
![Screenshot 2023-10-05 082129](https://github.com/ampslive/EasyLaundry/assets/134363792/75776432-6d39-4d66-a2bf-2de9739fe5a3)
![Screenshot 2023-10-05 091614](https://github.com/ampslive/EasyLaundry/assets/134363792/9a0630bf-ed74-4a00-acd8-406c30bf98e9)
![Screenshot 2023-10-05 092303](https://github.com/ampslive/EasyLaundry/assets/134363792/7abe8cfa-9315-4ed7-9825-d3fc9f551e07)
